---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: downloading {{ rke2_url }} to {{ rke2_exe }}
  become: true
  become_user: root
  get_url:
    url: '{{ rke2_url }}'
    dest: '{{ rke2_exe }}'
    checksum: '{{ rke2_checksum }}'
    mode: 0755
- name: linking {{ rke2_link }} to {{ rke2_exe }}
  become: true
  become_user: root
  file:
    src: '{{ rke2_exe }}'
    dest: '{{ rke2_link }}'
    state: link
